services:

  abrantes-database:
    image: postgres:16
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ./postgre-data:/var/lib/postgresql/data
    env_file: ./env-demo/db.env
    networks:
      - abrantes-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d estetica_abrantes"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

  servidor-mailhog:
    image: mailhog/mailhog:latest
    networks:
      - abrantes-network
    ports:
      - "8025:8025"

  abrantes-application:
    build:
      context: .
      dockerfile: Dockerfile
    image: abrantes-deploy
    env_file: ./env-demo/app.env
    environment:
      DB_HOST: abrantes-database
      SPRING_MAIL_HOST: servidor-mailhog
    networks:
      - abrantes-network
    ports:
      - "8080:8080"
    depends_on:
      abrantes-database:
        condition: service_healthy
      servidor-mailhog:
        condition: service_started

networks:
  abrantes-network:
    driver: bridge